"""initial schema

Revision ID: 8ca0b8794d7d
Revises: 
Create Date: 2026-05-25 23:25:14.525755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import control_plane.db.tables


# revision identifiers, used by Alembic.
revision: str = '8ca0b8794d7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('zulip_bot_id', sa.Integer(), nullable=False),
    sa.Column('zulip_bot_email', sa.String(length=255), nullable=False),
    sa.Column('zulip_api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('zulip_outgoing_token_encrypted', sa.String(length=255), nullable=False),
    sa.Column('context_message_count', sa.Integer(), nullable=False),
    sa.Column('readable_channels', sa.JSON(), nullable=False),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('provisioning_status', sa.String(length=32), nullable=False),
    sa.Column('is_bastion', sa.Boolean(), nullable=False),
    sa.Column('can_exec', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('runtime_kind', sa.String(length=32), nullable=False),
    sa.Column('runtime_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('zulip_bot_email')
    )
    op.create_table('archetypes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('context_message_count', sa.Integer(), nullable=False),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('mcp_servers', sa.JSON(), nullable=False),
    sa.Column('runtime_kind', sa.String(length=32), nullable=False),
    sa.Column('runtime_config', sa.JSON(), nullable=False),
    sa.Column('created_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('related_agent_id', sa.Uuid(), nullable=True),
    sa.Column('related_channel', sa.String(length=255), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pool_bots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zulip_bot_id', sa.Integer(), nullable=False),
    sa.Column('zulip_bot_email', sa.String(length=255), nullable=False),
    sa.Column('zulip_api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('zulip_outgoing_token_encrypted', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_name', sa.String(length=255), nullable=True),
    sa.Column('current_session_id', sa.Uuid(), nullable=True),
    sa.Column('last_active_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zulip_bot_email')
    )
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('cron_expression', sa.String(length=255), nullable=True),
    sa.Column('run_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('next_run_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_jobs_next_run_at'), 'scheduled_jobs', ['next_run_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('archetype_snapshot', sa.JSON(), nullable=False),
    sa.Column('pool_bot_id', sa.Uuid(), nullable=True),
    sa.Column('memory_ns', sa.String(length=512), nullable=False),
    sa.Column('granted_caps', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_index(op.f('ix_scheduled_jobs_next_run_at'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_table('pool_bots')
    op.drop_table('events')
    op.drop_table('archetypes')
    op.drop_table('agents')
    # ### end Alembic commands ###
