"""interactive artifacts tables

Revision ID: cbc2e4768e4f
Revises: 8ca0b8794d7d
Create Date: 2026-05-26 01:06:28.274285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import control_plane.db.tables


# revision identifiers, used by Alembic.
revision: str = 'cbc2e4768e4f'
down_revision: Union[str, Sequence[str], None] = '8ca0b8794d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactive_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('creator_agent_id', sa.Uuid(), nullable=False),
    sa.Column('source_channel', sa.String(length=255), nullable=False),
    sa.Column('source_topic', sa.String(length=255), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('conversation_type', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('storage_backend', sa.String(length=32), nullable=False),
    sa.Column('storage_ref', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactive_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.String(length=255), nullable=False),
    sa.Column('payload_full', sa.JSON(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('summary_model', sa.String(length=128), nullable=True),
    sa.Column('summary_status', sa.String(length=16), nullable=False),
    sa.Column('zulip_message_id', sa.Integer(), nullable=True),
    sa.Column('agent_job_ref', sa.Text(), nullable=True),
    sa.Column('created_at', control_plane.db.tables.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'submission_id', name='uq_submission_artifact_subid'),
    sa.UniqueConstraint('artifact_id', name='uq_submission_artifact')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interactive_submissions')
    op.drop_table('interactive_artifacts')
    # ### end Alembic commands ###
